title:             쏭's 블로그
email:             korea.sesong@gmail.com
description:       쏭's D-Log 블로그
author:            songsungeun
baseurl:           ""
url:               "http://songsungeun.github.io"

# Social Profiles
twitter_username:  
github_username:   Songsungeun
facebook_username: 

# Build settings
markdown:          kramdown

highlighter: rouge
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
